spring:
  application:
    name: sayhello


eureka:
  instance:
    hostname: sayhello
    preferIpAddress: true #this was done for example purposes only
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
          defaultZone: http://localhost:8761/eureka