spring:
  application:
    name: sayhello

server:
  port: 8090

eureka:
  instance:
    hostname: sayhello
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
          defaultZone: http://localhost:8761/eureka